# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5
sudo: false

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=pypy

before_install:
  - python --version
  - uname -a
  - lsb_release -a

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -U tox twine
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

# command to run tests, e.g. python setup.py test
script:
  - tox -v

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

before_cache:
  - rm -fr $HOME/.cache/pip/log

cache:
  diretories:
    - $HOME/.cache/pip

notifications:
  email:
    on_sucess: never
    on_failure: always
